### PR TITLE
Update power_measurement.adoc

### PR DESCRIPTION
**Pull request by s-idgunji**
Proposed changes based on supported flow for power in v1.0

### CODE REVIEW

**Review by TheKanter — APPROVED** [review]
LGTM

**Comment by sub-mod** [comment]
change "master" to mclommons/master

**Comment by s-idgunji** [comment]
@TheKanter  and @sub-mod   -  I have merged 1 commit into master , can you confirm that it's ok ?

**Comment by sub-mod** [comment]
can you find those changes here https://github.com/mlcommons/inference_policies ?

**Pull request merged**
